### ISSUE TITLE
cuda or not cuda?

### ISSUE THREAD

**Issue by ActonMartin** [victoresque/pytorch-template#74]
I have a gpu ,so I set "n_gpu": 1. And "base_trainer.py"(line 17) set model to cuda. And "trainer.py"(line 42) set input to cuda. But when start my Dataset, the error appears. 
`Trainable parameters: 31042369
Traceback (most recent call last):
  File "train.py", line 68, in <module>
    main(config)
  File "train.py", line 49, in main
    trainer.train()
  File "E:\kaggle\pytorch-template\base\base_trainer.py", line 66, in train
    result = self._train_epoch(epoch)
  File "E:\kaggle\pytorch-template\trainer\trainer.py", line 47, in _train_epoch
    output = self.model(data)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\kaggle\pytorch-template\model\model.py", line 117, in forward
    x1 = self.inc(x)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\kaggle\pytorch-template\model\model.py", line 42, in forward
    return self.double_conv(x)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same`
It makes me feel confused.I don't have idea.

**Comment by ActonMartin** [comment]
> I have a gpu ,so I set "n_gpu": 1. And "base_trainer.py"(line 17) set model to cuda. And "trainer.py"(line 42) set input to cuda. But when start my Dataset, the error appears.
> `Trainable parameters: 31042369 Traceback (most recent call last): File "train.py", line 68, in <module> main(config) File "train.py", line 49, in main trainer.train() File "E:\kaggle\pytorch-template\base\base_trainer.py", line 66, in train result = self._train_epoch(epoch) File "E:\kaggle\pytorch-template\trainer\trainer.py", line 47, in _train_epoch output = self.model(data) File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__ result = self.forward(*input, **kwargs) File "E:\kaggle\pytorch-template\model\model.py", line 117, in forward x1 = self.inc(x) File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__ result = self.forward(*input, **kwargs) File "E:\kaggle\pytorch-template\model\model.py", line 42, in forward return self.double_conv(x) File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__ result = self.forward(*input, **kwargs) File "D:\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 100, in forward input = module(input) File "D:\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__ result = self.forward(*input, **kwargs) File "D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 349, in forward return self._conv_forward(input, self.weight) File "D:\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 346, in _conv_forward self.padding, self.dilation, self.groups) RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same`
> It makes me feel confused.I don't have idea.

I find CRUX of the problem! It's definition of the model's forward. There is the origin code.
`    def forward(self, x):
        x = torch.as_tensor(x, dtype=torch.float)
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)
        x5 = self.down4(x4)
        x = self.up1(x5, x4)
        x = self.up2(x, x3)
        x = self.up3(x, x2)
        x = self.up4(x, x1)
        logits = self.outc(x)
        return logits`
there are two ways.
1.delete  "x = torch.as_tensor(x, dtype=torch.float) "
or 
2.It needs to make it transforms into device('cuda').
let it changes to "x = torch.as_tensor(x, dtype=torch.float).to(device="cuda")"
